### ISSUE TITLE
MAP ERROR

### ISSUE THREAD

**Issue by kriiszmae** [TerableCoder/Tera-NA-Opcodes#1]
When i try to drop files in the \map\ folder into your proxy's \node_modules\tera-data\map\ folder i get this errors
![explorer_aera2ZbvQ6](https://user-images.githubusercontent.com/47244732/58754502-ff6ee600-84d1-11e9-8936-a33106af8e8e.png)
![explorer_usUVjYAS3d](https://user-images.githubusercontent.com/47244732/58754503-ff6ee600-84d1-11e9-9dfb-89f48aea25d7.png)
![explorer_2VNCsLcEsU](https://user-images.githubusercontent.com/47244732/58754504-ff6ee600-84d1-11e9-95be-40cc45e1dcbb.png)
![explorer_fxTQNU1vfY](https://user-images.githubusercontent.com/47244732/58754505-ff6ee600-84d1-11e9-94de-49b76f2778fe.png)
![explorer_0lITJpynWZ](https://user-images.githubusercontent.com/47244732/58754506-00077c80-84d2-11e9-8876-1fbc15577668.png)
![explorer_6gAIua73fw](https://user-images.githubusercontent.com/47244732/58754507-00077c80-84d2-11e9-86c3-76a18826bebf.png)
![explorer_xsqAMWXmgT](https://user-images.githubusercontent.com/47244732/58754508-00077c80-84d2-11e9-8748-b2efe910f1aa.png)

**Comment by TerableCoder** [comment]
you probably already moved it

**Comment by kriiszmae** [comment]
this is the first time toh i download this app. Btw, im on eu server

**Comment by TerableCoder** [comment]
just redownload it and then move it into the folder
